---
shared:
  :flipflop_features:
    - id
    - key
    - enabled
    - created_at
    - updated_at
  :audits:
    - id
    - auditable_id
    - auditable_type
    - associated_id
    - associated_type
    - user_id
    - user_type
    - username
    - action
    - audited_changes
    - version
    - comment
    - remote_address
    - request_uuid
    - created_at
  :good_job_settings:
    - id
    - created_at
    - updated_at
    - key
    - value
  :good_job_processes:
    - id
    - created_at
    - updated_at
    - state
    - lock_type
  :good_job_executions:
    - id
    - created_at
    - updated_at
    - active_job_id
    - job_class
    - queue_name
    - serialized_params
    - scheduled_at
    - finished_at
    - error
    - error_event
    - error_backtrace
    - process_id
    - duration
  :good_job_batches:
    - id
    - created_at
    - updated_at
    - description
    - serialized_properties
    - on_finish
    - on_success
    - on_discard
    - callback_queue_name
    - callback_priority
    - enqueued_at
    - discarded_at
    - finished_at
    - jobs_finished_at
  :good_jobs:
    - id
    - queue_name
    - priority
    - serialized_params
    - scheduled_at
    - performed_at
    - finished_at
    - error
    - created_at
    - updated_at
    - active_job_id
    - concurrency_key
    - cron_key
    - retried_good_job_id
    - cron_at
    - batch_id
    - batch_callback_id
    - is_discrete
    - executions_count
    - job_class
    - error_event
    - labels
    - locked_by_id
    - locked_at
  :schools:
    - transit_travel_duration
    - transit_travel_distance
    - drive_travel_duration
    - drive_travel_distance
  :school_contacts:
    - name
    - email_address
    - first_name
    - last_name
  :users:
    - first_name
    - last_name
    - email
  :mentors:
    - id
    - first_name
    - last_name
    - trn
    - created_at
    - updated_at
  :providers:
    - email_address
    - telephone
  :sessions:
    - id
    - session_id
    - data
    - created_at
    - updated_at
