---
HOSTING_ENV: production

# Primary hostname for the Funding Mentors service
CLAIMS_HOST: claim-funding-for-mentor-training.education.gov.uk
# Additional hostnames that may be used – e.g. the CDN origin (comma separated)
CLAIMS_HOSTS: claim-funding-for-mentor-training.education.gov.uk,track-and-pay-production.teacherservices.cloud

# Primary hostname for the School Placements service
PLACEMENTS_HOST: manage-school-placements.education.gov.uk
# Additional hostnames that may be used – e.g. the CDN origin (comma separated)
PLACEMENTS_HOSTS: manage-school-placements.education.gov.uk,manage-school-placements-production.teacherservices.cloud

# API integrations
GIAS_CSV_BASE_URL: https://ea-edubase-api-prod.azurewebsites.net/edubase/downloads/public
PUBLISH_BASE_URL: https://api.publish-teacher-training-courses.service.gov.uk/
TEACHING_RECORD_BASE_URL: https://teacher-qualifications-api.education.gov.uk/
TEACHING_RECORD_API_MINOR_VERSION: 20240416

# User authentication
SIGN_IN_METHOD: dfe-sign-in
DFE_SIGN_IN_ISSUER_URL: https://oidc.signin.education.gov.uk
CLAIMS_DFE_SIGN_IN_CLIENT_ID: ittMentorTrackPay
PLACEMENTS_DFE_SIGN_IN_CLIENT_ID: ittMentorSchoolPlacement

# DfE Analytics gem
BIGQUERY_TABLE_NAME: events
BIGQUERY_PROJECT_ID: rugged-abacus-218110
BIGQUERY_DATASET: itt_mentor_events_production
BIGQUERY_MAINTENANCE_WINDOW: "04-06-2024 18:00..04-06-2024 18:10"
