---
HOSTING_ENV: qa
SKYLIGHT_ENV: qa

# Primary hostname for the Funding Mentors service
CLAIMS_HOST: qa.claim-funding-for-mentor-training.education.gov.uk
# Additional hostnames that may be used â€“ e.g. the CDN origin (comma separated)
CLAIMS_HOSTS: qa.claim-funding-for-mentor-training.education.gov.uk,track-and-pay-qa.test.teacherservices.cloud

# API integrations
GIAS_CSV_BASE_URL: https://ea-edubase-api-prod.azurewebsites.net/edubase/downloads/public
PUBLISH_BASE_URL: https://qa.api.publish-teacher-training-courses.service.gov.uk
TEACHING_RECORD_BASE_URL: https://preprod.teacher-qualifications-api.education.gov.uk
TEACHING_RECORD_API_MINOR_VERSION: 20240416

# User authentication
SIGN_IN_METHOD: persona

# DfE Analytics gem
BIGQUERY_TABLE_NAME: events
BIGQUERY_PROJECT_ID: rugged-abacus-218110
BIGQUERY_DATASET: itt_mentor_events_qa
