---
HOSTING_ENV: sandbox

# Primary hostname for the Funding Mentors service
CLAIMS_HOST: sandbox.claim-funding-for-mentor-training.education.gov.uk
# Additional hostnames that may be used – e.g. the CDN origin (comma separated)
CLAIMS_HOSTS: sandbox.claim-funding-for-mentor-training.education.gov.uk,track-and-pay-sandbox.teacherservices.cloud

# Primary hostname for the School Placements service
PLACEMENTS_HOST: sandbox.manage-school-placements.education.gov.uk
# Additional hostnames that may be used – e.g. the CDN origin (comma separated)
PLACEMENTS_HOSTS: sandbox.manage-school-placements.education.gov.uk,manage-school-placements-sandbox.teacherservices.cloud

# API integrations
GIAS_CSV_BASE_URL: https://ea-edubase-api-prod.azurewebsites.net/edubase/downloads/public
PUBLISH_BASE_URL: https://api.publish-teacher-training-courses.service.gov.uk
TEACHING_RECORD_BASE_URL: https://preprod.teacher-qualifications-api.education.gov.uk
TEACHING_RECORD_API_MINOR_VERSION: 20240416

# User authentication
SIGN_IN_METHOD: persona
CLAIMS_DFE_SIGN_IN_CLIENT_ID: ittMentorTrackPay

# DfE Analytics gem
BIGQUERY_TABLE_NAME: events
BIGQUERY_PROJECT_ID: rugged-abacus-218110
BIGQUERY_DATASET: itt_mentor_events_sandbox
