---
HOSTING_ENV: staging
SKYLIGHT_ENV: staging

# Primary hostname for the Funding Mentors service
CLAIMS_HOST: staging.claim-funding-for-mentor-training.education.gov.uk
# Additional hostnames that may be used – e.g. the CDN origin (comma separated)
CLAIMS_HOSTS: staging.claim-funding-for-mentor-training.education.gov.uk,track-and-pay-staging.test.teacherservices.cloud,track-and-pay-temp.test.teacherservices.cloud

# Primary hostname for the School Placements service
PLACEMENTS_HOST: staging.manage-school-placements.education.gov.uk
# Additional hostnames that may be used – e.g. the CDN origin (comma separated)
PLACEMENTS_HOSTS: staging.manage-school-placements.education.gov.uk,manage-school-placements-staging.test.teacherservices.cloud,manage-school-placements-temp.test.teacherservices.cloud

# API integrations
GIAS_CSV_BASE_URL: https://ea-edubase-api-prod.azurewebsites.net/edubase/downloads/public
PUBLISH_BASE_URL: https://staging.api.publish-teacher-training-courses.service.gov.uk
TEACHING_RECORD_BASE_URL: https://preprod.teacher-qualifications-api.education.gov.uk
TEACHING_RECORD_API_MINOR_VERSION: 20240416

# User authentication
SIGN_IN_METHOD: dfe-sign-in
CLAIMS_DFE_SIGN_IN_CLIENT_ID: ittMentorTrackPay
DFE_SIGN_IN_ISSUER_URL: https://test-oidc.signin.education.gov.uk
PLACEMENTS_DFE_SIGN_IN_CLIENT_ID: ittMentorSchoolPlacement

# DfE Analytics gem
BIGQUERY_TABLE_NAME: events
BIGQUERY_PROJECT_ID: rugged-abacus-218110
BIGQUERY_DATASET: itt_mentor_events_staging
