apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: itt-dv.cluster3
  namespace: development
spec:
  hosts:
  - "itt.dv.cluster3.development.teacherservices.cloud"     # must match Host header / SNI you test with
  gateways:
  - istio-ingress/istio-ingress-gateway   # namespace/name of your Gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: itt.development.svc.cluster.local
        port:
          number: 80